const itemsToMonitor = [

    "\"OPCUA\".BB01_CMD_LIG",

    "\"OPCUA\".BB01_CMD_EMG",

    "\"OPCUA\".BB01_CMD_MANUT",

    "\"OPCUA\".BB01_CMD_AUTO_MAN",

    "\"OPCUA\".BB01_CMD_LR",

    "\"OPCUA\".BB01_CMD_REFERENCE",

    "\"OPCUA\".BB01_OUT",

    "\"OPCUA\".BB01_OPERSTATUS",

    "\"OPCUA\".BB01_FAULTCODE",

    "\"OPCUA\".BB02_CMD_LIG",

    "\"OPCUA\".BB02_CMD_EMG",

    "\"OPCUA\".BB02_CMD_MANUT",

    "\"OPCUA\".BB02_CMD_AUTO_MAN",

    "\"OPCUA\".BB02_CMD_LR",

    "\"OPCUA\".BB02_CMD_REFERENCE",

    "\"OPCUA\".BB02_OUT",

    "\"OPCUA\".BB02_OPERSTATUS",

    "\"OPCUA\".BB02_FAULTCODE",

    "\"OPCUA\".BB03_CMD_LIG",

    "\"OPCUA\".BB03_CMD_EMG",

    "\"OPCUA\".BB03_CMD_MANUT",

    "\"OPCUA\".BB03_CMD_AUTO_MAN",

    "\"OPCUA\".BB03_CMD_LR",

    "\"OPCUA\".BB03_CMD_REFERENCE",

    "\"OPCUA\".BB03_OUT",

    "\"OPCUA\".BB03_OPERSTATUS",

    "\"OPCUA\".BB03_FAULTCODE",

    "\"OPCUA\".BB04_CMD_LIG",

    "\"OPCUA\".BB04_CMD_EMG",

    "\"OPCUA\".BB04_CMD_MANUT",

    "\"OPCUA\".BB04_CMD_AUTO_MAN",

    "\"OPCUA\".BB04_CMD_LR",

    "\"OPCUA\".BB04_CMD_REFERENCE",

    "\"OPCUA\".BB04_OUT",

    "\"OPCUA\".BB04_OPERSTATUS",

    "\"OPCUA\".BB04_FAULTCODE",


    "\"OPCUA\".BB05_CMD_LIG",

    "\"OPCUA\".BB05_CMD_EMG",

    "\"OPCUA\".BB05_CMD_MANUT",

    "\"OPCUA\".BB05_CMD_AUTO_MAN",

    "\"OPCUA\".BB05_CMD_LR",

    "\"OPCUA\".BB05_CMD_REFERENCE",

    "\"OPCUA\".BB05_OUT",

    "\"OPCUA\".BB05_OPERSTATUS",

    "\"OPCUA\".BB05_FAULTCODE",

    "\"OPCUA\".BB06_CMD_LIG",

    "\"OPCUA\".BB06_CMD_EMG",

    "\"OPCUA\".BB06_CMD_MANUT",

    "\"OPCUA\".BB06_CMD_AUTO_MAN",

    "\"OPCUA\".BB06_CMD_LR",

    "\"OPCUA\".BB06_CMD_REFERENCE",

    "\"OPCUA\".BB06_OUT",

    "\"OPCUA\".BB06_OPERSTATUS",

    "\"OPCUA\".BB06_FAULTCODE",

    "\"OPCUA_FLOW\".FT01",

    "\"OPCUA_FLOW\".FT02",

    "\"OPCUA_FLOW\".FT03",

    "\"OPCUA_FLOW\".FT04",

    "\"OPCUA_PRESSURE\".PT01",

    "\"OPCUA_PRESSURE\".PT02",

    "\"OPCUA_PRESSURE\".PT03",

    "\"OPCUA_PRESSURE\".PT04",

    "\"OPCUA_PRESSURE\".PT05",

    "\"OPCUA_PRESSURE\".PT06",

    "\"OPCUA_PRESSURE\".PT07",

    "\"OPCUA_LEVEL\".LT01",

    "\"OPCUA_VALVES\".XV01_CMD_LIG",

    "\"OPCUA_VALVES\".XV01_CMD_MANUT",

    "\"OPCUA_VALVES\".XV01_CMD_AUTOMAN",

    "\"OPCUA_VALVES\".XV01_CLOSE",

    "\"OPCUA_VALVES\".XV01_OPEN",

    "\"OPCUA_VALVES\".XV01_OPENALM",

    "\"OPCUA_VALVES\".XV01_CLOSEALM",

    "\"OPCUA_VALVES\".XV02_CMD_LIG",

    "\"OPCUA_VALVES\".XV02_CMD_MANUT",

    "\"OPCUA_VALVES\".XV02_CMD_AUTOMAN",

    "\"OPCUA_VALVES\".XV02_CLOSE",

    "\"OPCUA_VALVES\".XV02_OPEN",

    "\"OPCUA_VALVES\".XV02_OPENALM",

    "\"OPCUA_VALVES\".XV02_CLOSEALM",

    "\"OPCUA_VALVES\".XV03_CMD_LIG",

    "\"OPCUA_VALVES\".XV03_CMD_MANUT",

    "\"OPCUA_VALVES\".XV03_CMD_AUTOMAN",

    "\"OPCUA_VALVES\".XV03_CLOSE",

    "\"OPCUA_VALVES\".XV03_OPEN",

    "\"OPCUA_VALVES\".XV03_OPENALM",

    "\"OPCUA_VALVES\".XV03_CLOSEALM",

    "\"OPCUA_VALVES\".XV04_CMD_LIG",

    "\"OPCUA_VALVES\".XV04_CMD_MANUT",

    "\"OPCUA_VALVES\".XV04_CMD_AUTOMAN",

    "\"OPCUA_VALVES\".XV04_CLOSE",

    "\"OPCUA_VALVES\".XV04_OPEN",

    "\"OPCUA_VALVES\".XV04_OPENALM",

    "\"OPCUA_VALVES\".XV04_CLOSEALM",

    "\"OPCUA_VALVES\".XV05_CMD_LIG",

    "\"OPCUA_VALVES\".XV05_CMD_MANUT",

    "\"OPCUA_VALVES\".XV05_CMD_AUTOMAN",

    "\"OPCUA_VALVES\".XV05_CLOSE",

    "\"OPCUA_VALVES\".XV05_OPEN",

    "\"OPCUA_VALVES\".XV05_OPENALM",

    "\"OPCUA_VALVES\".XV05_CLOSEALM",

    "\"OPCUA_VALVES\".XV06_CMD_LIG",

    "\"OPCUA_VALVES\".XV06_CMD_MANUT",

    "\"OPCUA_VALVES\".XV06_CMD_AUTOMAN",

    "\"OPCUA_VALVES\".XV06_CLOSE",

    "\"OPCUA_VALVES\".XV06_OPEN",

    "\"OPCUA_VALVES\".XV06_OPENALM",

    "\"OPCUA_VALVES\".XV06_CLOSEALM",

    "\"OPCUA_VALVES\".XV07_CMD_LIG",

    "\"OPCUA_VALVES\".XV07_CMD_MANUT",

    "\"OPCUA_VALVES\".XV07_CMD_AUTOMAN",

    "\"OPCUA_VALVES\".XV07_CLOSE",

    "\"OPCUA_VALVES\".XV07_OPEN",

    "\"OPCUA_VALVES\".XV07_OPENALM",

    "\"OPCUA_VALVES\".XV07_CLOSEALM",

    "\"OPCUA_VALVES\".XV08_CMD_LIG",

    "\"OPCUA_VALVES\".XV08CMD_MANUT",

    "\"OPCUA_VALVES\".XV08_CMD_AUTOMAN",

    "\"OPCUA_VALVES\".XV08_CLOSE",

    "\"OPCUA_VALVES\".XV08_OPEN",

    "\"OPCUA_VALVES\".XV08_OPENALM",

    "\"OPCUA_VALVES\".XV08_CLOSEALM",
];
module.exports = itemsToMonitor
